# Site settings
title: Thesis by Blogpost
email: lastname.firstname@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "https://laurent-dinh.github.io/"

# Sidebar settings
description: Laurent Dinh. Research Scientist at Google Brain.

# Social icons
linkedin: laurent-dinh-b9287237
github: laurent-dinh
twitter: laurent_dinh
scholar: h7OHSkoAAAAJ

footer: © Laurent Dinh

# Build settings
markdown: kramdown
exclude: ['academicons-1.8.0/README.md']
